dbt_adv:
  outputs:
    prod:
      account: snowflake_account_
      database: dbt_dv
      password: add_pass
      role: accountadmin
      schema: public
      threads: 1
      type: snowflake
      user: debora
      warehouse: compute_wh
  target: prod
